get-appxpackage *3dbuilder* | remove-appxpackage
get-appxpackage *alarms* | remove-appxpackage
get-appxpackage *appconnector* | remove-appxpackage
get-appxpackage *communicationsapps* | remove-appxpackage
get-appxpackage *camera* | remove-appxpackage
get-appxpackage *feedback* | remove-appxpackage
get-appxpackage *officehub* | remove-appxpackage
get-appxpackage *getstarted* | remove-appxpackage
get-appxpackage *skypeapp* | remove-appxpackage
get-appxpackage *zunemusic* | remove-appxpackage
get-appxpackage *zune* | remove-appxpackage
get-appxpackage *maps* | remove-appxpackage
get-appxpackage *messaging* | remove-appxpackage
get-appxpackage *solitaire* | remove-appxpackage
get-appxpackage *wallet* | remove-appxpackage
get-appxpackage *bingfinance* | remove-appxpackage
get-appxpackage *bing* | remove-appxpackage
get-appxpackage *zunevideo* | remove-appxpackage
get-appxpackage *bingnews* | remove-appxpackage
get-appxpackage *onenote* | remove-appxpackage
get-appxpackage *oneconnect* | remove-appxpackage
get-appxpackage *mspaint* | remove-appxpackage
get-appxpackage *people* | remove-appxpackage
get-appxpackage *commsphone* | remove-appxpackage
get-appxpackage *windowsphone* | remove-appxpackage
get-appxpackage *phone* | remove-appxpackage
get-appxpackage *bingsports* | remove-appxpackage
get-appxpackage *sway* | remove-appxpackage
get-appxpackage *3d* | remove-appxpackage
get-appxpackage *soundrecorder* | remove-appxpackage
get-appxpackage *holographic* | remove-appxpackage
get-appxpackage *xbox* | remove-appxpackage
get-appxpackage *WindowsAlarms* | remove-appxpackage
get-appxpackage *XboxSpeechToTextOverlay* | remove-appxpackage
get-appxpackage *XboxIdentityProvider* | remove-appxpackage
get-appxpackage *XboxGameOverlay* | remove-appxpackage
get-appxpackage *Xbox.TCUI* | remove-appxpackage
get-appxpackage *A278AB0D.DisneyMagicKingdoms* | remove-appxpackage
get-appxpackage *king.com.BubbleWitch3Saga* | remove-appxpackage
get-appxpackage *king.com.CandyCrushSodaSaga* | remove-appxpackage
get-appxpackage *fitbitcoach* | remove-appxpackage
Get-AppxPackage *dolbyaccess* | Remove-AppxPackage
Get-AppxPackage *DolbyAudioPremium* | Remove-AppxPackage
Get-AppxPackage *picsart* | Remove-AppxPackage
Get-AppxPackage *phototastic* | Remove-AppxPackage
Get-AppxPackage *windowsphone* | Remove-AppxPackage
Get-AppxPackage *GetHelp* | Remove-AppxPackage
Get-AppxPackage *Microsoft.whiteboard* | Remove-AppxPackage
Get-AppxPackage *Microsoft.Office.Sway* | Remove-AppxPackage